### ISSUE TITLE
酷狗安卓app本地调试访问MiniApp is not defined

### ISSUE THREAD

**Issue by linwh203** [kugou-miniapp/kugou-cli#3]
![image](https://user-images.githubusercontent.com/22272042/103785803-9e789e00-5076-11eb-94b7-f1eb3aaa8039.png)
通过酷狗小程序后台，本地调试扫二维码，
console报错MiniApp is not defined
![image](https://user-images.githubusercontent.com/22272042/103785970-cd8f0f80-5076-11eb-8575-a748e6305079.png)

**Comment by L-Chris** [comment]
> ![image](https://user-images.githubusercontent.com/22272042/103785803-9e789e00-5076-11eb-94b7-f1eb3aaa8039.png)
> 通过酷狗小程序后台，本地调试扫二维码，
> console报错MiniApp is not defined
> ![image](https://user-images.githubusercontent.com/22272042/103785970-cd8f0f80-5076-11eb-8575-a748e6305079.png)

麻烦修改代码MiniApp => window.MiniApp，下个版本修复

**Comment by kugouMiniapp** [comment]
Fix
